FROM golang:1.21.6

WORKDIR /app

COPY go.mod .
COPY main.go .

RUN go get
RUN go build -o bin .

ENV PORT "9000"
ENV CONNECTION_STRING="mongodb+srv://simong:Esketit_2002@cluster0.zqam4sj.mongodb.net/"
ENV DATABASE_NAME="task_scheduler"
ENV USERNAME="simong"
ENV PASSWORD="Esketit_2002"

ENTRYPOINT [ "/app/bin" ]

